spring.application.name=demo

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.urls[0].name=payment-api
springdoc.swagger-ui.urls[0].url=/openapi/payment-api.yaml
